on:
  push:
    branches:
      - f35
    tags:
      - tag
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:36
      options: --privileged=true
    steps:
      - uses: actions/checkout@v2
        with:
          path: "fedora-release"
      - name: Install dependencies
        run: |
          sudo dnf -y update
          sudo dnf -y install \
            rpmdevtools \
            mock fedpkg
      - name: Build RPMS
        run: |
          sed -i "s/serenelinux-release/fedora-release/g" .git/config
          sudo fedpkg --release f35 mockbuild
      - name: Archive generated rpms
        uses: actions/upload-artifact@v2
        with:
          name: rpm-fedora-release
          path: results_fedora-release
      
      